### ISSUE TITLE
Styling the sidebar

### ISSUE THREAD

**Issue by leocrawf** [shripalsoni04/nativescript-angular-drawer-template#4]
I tried styling the header of the sidebar using the this code on the core.light.android.css file but nothing changed in the app:

     .sidedrawer-header{height:148;background-color:#564215;width:100%}.

What I am I doing wrong?

**Comment by shripalsoni04** [comment]
To change style of side-drawer, you need to do changes in [css file of side-drawer-page.component](https://github.com/shripalsoni04/ns-ng-drawer-template-demo/blob/master/app/modules/shared/side-drawer-page/side-drawer-page.component.css). Changes in app.css will not be reflected because, rule for `.sidedrawer-header` class is already defined in the css file of that component.

**Comment by leocrawf** [comment]
By golly I am stupid! Major overlook. Thank you.
